import express from'express';import cors from'cors';import dotenv from'dotenv';import mongoose from'mongoose';import jwt from'jsonwebtoken';dotenv.config();const app=express();app.use(cors({origin:true,credentials:true}));app.use(express.json());
const MONGO=process.env.MONGO_URI||'';if(MONGO){mongoose.connect(MONGO).then(()=>console.log('MongoDB Connected')).catch(e=>console.error('MongoDB error',e.message));}
const users=[{email:'admin@kranthimetal.com',password:'123456',name:'Admin User',role:'Admin'},{email:'manager@kranthimetal.com',password:'123456',name:'Sales Manager',role:'Manager'},{email:'employee@kranthimetal.com',password:'123456',name:'Store Employee',role:'Employee'}];
const customers=[{id:1,name:'Sri Lakshmi Steels',phone:'9876543210',city:'Hyderabad',status:'Active'},{id:2,name:'Venkateshwara Traders',phone:'9848012345',city:'Vijayawada',status:'Active'}];
const materials=[{id:1,code:'MS-RB-12',name:'MS Round Bar',size:'12mm',stock:4200,rate:58},{id:2,code:'MS-ANG-50',name:'MS Angle',size:'50x50x6mm',stock:2600,rate:65}];
app.get('/',(req,res)=>res.json({ok:true,app:'KRANTHI METAL CRM'}));app.get('/api/health',(req,res)=>res.json({ok:true,app:'KRANTHI METAL CRM'}));
app.post('/api/auth/login',(req,res)=>{const{email,password}=req.body;const u=users.find(x=>x.email===email&&x.password===password);if(!u)return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({email:u.email,role:u.role},process.env.JWT_SECRET||'secret',{expiresIn:'7d'});res.json({token,user:{email:u.email,name:u.name,role:u.role}})});
app.get('/api/customers',(req,res)=>res.json(customers));app.get('/api/materials',(req,res)=>res.json(materials));app.post('/api/quotations',(req,res)=>res.json({ok:true,quotation:req.body}));
const port=process.env.PORT||5000;app.listen(port,()=>console.log('Server running on '+port));
